#!/usr/bin/env bash

JENKINS_ROOT=/usr/local/server/jenkins
JENKINS_FILENAME=jenkins.war

PORT=8800
USER=jenkins

start() {
  cd ${JENKINS_ROOT}
  su -c "nohup java -jar ${JENKINS_ROOT}/${JENKINS_FILENAME} --ajp13Port=-1 --httpPort=${PORT} &" ${USER}
}

stop() {
  PID=`jps |grep ${JENKINS_FILENAME} |awk '{print $1}'`
  kill -9 ${PID}
}

status() {
  ps -ef|grep ${JENKINS_FILENAME}
}

case "$1" in
start)
  start
  ;;
stop)
  stop
  ;;
restart)
  stop
  start
  ;;
status)
  status
  ;;
*)
  printf 'Usage: %s {start|stop|restart|status}\n'
  exit 1
  ;;
esac